- name: Get Secrets
  hosts: localhost
  tasks:
   -  name: create secret files
      ansible.builtin.lineinfile:
        path: ~/{{item |split("/") |last}}.json
        line: "{{ lookup('hashi_vault', 'secret={{item}} token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False')}}"
        create: true
      loop:
        - "common/data/common"
        - "expense-{{env}}/data/{{role_name}}"
        - "rds/data/{{env}}"

   -  name: create common secrets
      ansible.builtin.shell: for i in $(ls ~/*.json); do echo -n $(cat $i) ; done | sed -e 's/}{/, /g' >~/secrets.json
