- name: Get Secrets
  hosts: localhost
  tasks:
#   -  name: create common file SSH secrets
#      ansible.builtin.lineinfile:
#        path: ~/secrets.json
#        line: "{{ lookup('hashi_vault', 'secret=common/data/common token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False')}}"
#        create: true
#
   -  name: create secret files
      ansible.builtin.lineinfile:
        path: ~/{{item |split("/") |last}}.json
        line: "{{ lookup('hashi_vault', 'secret={{item}} token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False')}}"
        create: true
      loop:
        - "common/data/common"
        - "expense-{{env}}/data/{{role_name}}"
        - "rds/data/{{env}}"

   -  name: create common secrets
      ansible.builtin.shell: for i in $(ls ~/*.json); do echo -n $(cat $i) ; done | sed -e 's/}{/, /' >~/secrets.json





#     ansible.builtin.lineinfile:
#       path: ~/apps.json
#       line: "{{ lookup('hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False')}}"
#       create: true
# Moved to a single task, getting all the secrets
#    - name: Create common Secrets file
#      ansible.builtin.lineinfile:
#         path: secrets
#         line: "{{lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False')}}"
#         create: yes

#    - name: Create App Secrets file
#      ansible.builtin.lineinfile:
#        path: ~/app.json
#        line: "{{lookup('hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False')}}"
#        create: yes

#    - name: Create Common Secret
#      ansible.builtin.shell: for i in $(ls ~/*.json); do echo -n $(cat $i) ;done | sed -e 's/}{/, /g' >~/secrets.json