- name: Get Secrets
  hosts: localhost
  tasks:
     - name: Create Common Secrets SSH file
       ansible.builtin.lineinfile:
         path: ~/secrets.json
         line: "{{lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False')}}"
         create: yes
