- name: Get Secrets
  hosts: localhost
  tasks:
   -  name: create file with secrets
      ansible.builtin.lineinfile:
        path: /tmp/vault_secrets
        line: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False')}}"
        create: true

      






#    - name: Create common Secrets file
#      ansible.builtin.lineinfile:
#         path: secrets
#         line: "{{lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False')}}"
#         create: yes

#    - name: Create App Secrets file
#      ansible.builtin.lineinfile:
#        path: ~/app.json
#        line: "{{lookup('hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False')}}"
#        create: yes

#    - name: Create Common Secret
#      ansible.builtin.shell: for i in $(ls ~/*.json); do echo -n $(cat $i) ;done | sed -e 's/}{/, /g' >~/secrets.json