- name: Get Secrets
  hosts: localhost
  vars:
    ssh: "{{lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.shujathdevops.online:8200 validate_certs=False')}}"
  tasks:
    - name: Create Secrets file
      ansible.builtin.lineinfile:
         path: secrets.json
         line: "{{ssh}}"
         create: yes

