    - name: disable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: disable nodejs
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Add the Appl user
      ansible.builtin.user:
        name: expense


    - name: Remove Old contents
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create a directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Copy file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Download and Extract Apps contents
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes

    - name: Install nodejs dependencies
      community.general.npm:
        path: /app
        state: latest

    - name: Install python mysql client
      ansible.builtin.pip:
        name:
          - cryptography
          - PyMySQL
        executable: pip3.9

    - name: Load Schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql-dev.shujathdevops.online

    - name: Start service
      ansible.builtin.systemd_service:
        name: backend
        state: restarted
        enabled: true
        daemon_reload: true
