    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: Copy config file
      ansible.builtin.template:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: App pre-req-Remove-Create-Extract
      ansible.builtin.import_role:
        name: common
        tasks_from: app-pre-req

    - name: Start nginx
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx
        enabled: true
        daemon_reload: true






