    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Start MySQL Service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install python mysql client
      ansible.builtin.pip:
        name:
          - cryptography
          - PyMySQL
        executable: pip3.11

    - name: check DB connection with our own password
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{mysql_root_password}}"
        filter: version
        login_host: mysql-{{ env }}.shujathdevops.online
      register: mysql_db_connection
      ignore_errors: yes

    - name: Setup MySQL Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass {{mysql_root_password}}
      when: mysql_db_connection.failed is true
