    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Start MySQL Service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install python mysql client
      ansible.builtin.pip:
        name:
          - cryptography
          - PyMySQL
        executable: pip3.9

    - name: Get MySQL version with non-default credentials
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        filter: version
        login_host: mysql-{{ env }}.shujathdevops.online
      register: mysql_db_connection

    - name: printing mysql db connection details
      ansible.builtin.debug:
        msg: "{{ mysql_db_connection }}"

    - name: Setup MySQL Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass {{mysql_root_password}}
      when: mysql_connection_output.failed is true
