format_version: 10
pipelines:
  backend:
    group: Ansible
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-649cad1:
        git: https://github.com/s-devops-i1/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:Sth1tvnR/+8e2DhsGT7yAg==:t7wHKwQ/Qkojdh7/WZTvMl3dL1dMeB9iKnq/4pT30VE=
    stages:
      - DEV:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          environment_variables:
             env: dev
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            my-job-1:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - backend
                    command: bash
                    run_if: passed
      - QA:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            my-job-1:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - 03-vars.yml
                    command: ansible-playbook
                    run_if: passed
      - UAT:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            my-job-1:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - 03-vars.yml
                    command: ansible-playbook
                    run_if: passed
      - PROD:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            my-job-1:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - 03-vars.yml
                    command: ansible-playbook
                    run_if: passed
